print('===== DESAFIO 2 =====')
day = input('Digite o DIA em que nasceu: ')
month = input('Digite o MÊS em que nasceu: ')
year = input('Digite o ANO em que nasceu: ')
print('Você nasceu no dia', day, 'do', month, 'de', year + '!')
